In [4]:
import numpy as np

In [5]:
#size of array

In [6]:
n1 = np.array([1, 7, 13, 105])
print(n1.nbytes)

32


In [7]:
#elementwise comparison

In [8]:
a1 = np.array([3, 5])

In [9]:
a2 = np.array([2,5])

In [10]:
print("Comparison - greater")

Comparison - greater


In [11]:
print(np.greater(a1, a2))
print("Comparison - greater_equal")
print(np.greater_equal(a1, a2))
print("Comparison - less")
print(np.less(a1, a2))
print("Comparison - less_equal")
print(np.less_equal(a1, a2))

[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [12]:
#10 zeroes, 10 ones, 10fives, 10 tens, 10twentys, 10 fiftys

In [13]:
arr1 = np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
arr2 = np.ones(10)
print(arr2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [15]:
arr3 = np.ones(10)*5
print(arr3)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [16]:
arr4 = np.ones(10)*10
print(arr4)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [17]:
arr5 = np.ones(10)*20
print(arr5)

[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]


In [18]:
arr6 = np.ones(10)*50
print(arr6)

[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [19]:
arr7 = np.arange(30,70)
print(arr7)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [23]:
arr8 = np.arange(50,95)
print(arr8)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [24]:
arr9 = np.arange(20,80,2)
print(arr9)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [27]:
arr10 = np.arange(20,80,3)
print(arr10)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77]


In [62]:
n1 = np.random.randint(10,40,15)
print(n1)

[10 16 27 28 17 35 31 35 26 33 25 20 37 24 32]


In [63]:
n2 = np.random.randint(30,50,10)
print(n2)

[49 41 49 42 46 45 49 42 35 31]


In [64]:
n3 = np.random.randint(50,90,20)
print(n3)

[51 80 83 53 52 84 67 54 63 58 57 80 82 61 79 64 88 72 88 87]


In [65]:
#create any two arrays

In [70]:
n4 = np.array([11,22,33,44])
n5 = np.array([1,2,3,4])
print((n4+n5))
print((n4 - n5))
print((n4 * n5))
print((n4 / n5))

[12 24 36 48]
[10 20 30 40]
[ 11  44  99 176]
[11. 11. 11. 11.]


In [71]:
#3x4 matrix filled with values from 10 to 21

In [75]:
n6 = np.arange(10, 22).reshape([3, 4])
print (n6)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [76]:
n7 = np.eye(3)
print (n7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [77]:
matrix = np.array([[9, 9, 9], [8, 8, 8]])
 
dimensions = matrix.shape
rows, columns = dimensions
 
print("Rows:", rows)
print("Columns:", columns)

Rows: 2
Columns: 3


In [78]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [79]:
x = np.random.random((3,3,3))
print(x)

[[[0.68386489 0.16018841 0.21375544]
  [0.61914822 0.53961335 0.80563586]
  [0.11964872 0.62553781 0.27566688]]

 [[0.30222558 0.14619981 0.25670536]
  [0.21520802 0.08885448 0.96403278]
  [0.82062326 0.77093723 0.15814685]]

 [[0.84775402 0.2353931  0.50679611]
  [0.86453782 0.05797257 0.25059182]
  [0.32934149 0.11253072 0.54620085]]]


In [81]:
x = np.random.random((2,3,4,5))
print(x)

[[[[0.92899133 0.36629818 0.59043806 0.24279978 0.7206412 ]
   [0.61625074 0.52272262 0.18989967 0.18449419 0.44837202]
   [0.06572079 0.26101344 0.99603678 0.98923229 0.25574668]
   [0.12106012 0.73969136 0.67349442 0.98772008 0.3971649 ]]

  [[0.23798907 0.15088395 0.44300097 0.3568401  0.14880908]
   [0.45260672 0.41239074 0.62631034 0.23250126 0.44934668]
   [0.62263617 0.603978   0.69053193 0.21471983 0.02972251]
   [0.71060432 0.68585493 0.1286568  0.43784713 0.40064802]]

  [[0.95191401 0.16397541 0.38954531 0.92279007 0.67725444]
   [0.27044802 0.31921815 0.67120636 0.63085725 0.15984272]
   [0.4892166  0.76981626 0.98919709 0.19497272 0.26112064]
   [0.42353447 0.77672065 0.43837882 0.77582858 0.2624157 ]]]


 [[[0.60978449 0.87725112 0.18452709 0.87258763 0.49447974]
   [0.42265736 0.27859286 0.56241483 0.35588023 0.3276664 ]
   [0.50093815 0.0053467  0.50221936 0.72463252 0.66668888]
   [0.88470059 0.81302388 0.97534631 0.77060349 0.98650972]]

  [[0.10021952 0.25612882 0.61

In [83]:
l = [12.23, 13.32, 100, 36.32]
print("Original List:", l)
a = np.array(l)
print("One-dimensional NumPy array: ", a)




Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


In [84]:
x = np.arange(2, 11).reshape(3, 3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [85]:
x = np.arange(12,38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [86]:
print("Reverse array:")
x = x[::-1]
print(x) 

Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [87]:
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x) 

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


In [88]:
x = np.arange(7)
print("Original array:")
print(x)
print("Element-wise remainder of division:")
print(np.remainder(x, 5)) 

Original array:
[0 1 2 3 4 5 6]
Element-wise remainder of division:
[0 1 2 3 4 0 1]
